# Anthony Hughes II
## Homework #5
### Nov. 9, 2025

1. Pandas stands for either 'Panel Date' or 'Python Data Analysis'
1. Series and DataFrames
1. manipulate, prepare, model, and analyze
1. inplace
1. comma-seperated value, a plain text file to store tabular data
1. "N/A"

In [11]:
#7. 
import numpy as np

array = np.arange(12).reshape(2, 3, 2)

print(array)
print("Array shape:", array.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
Array shape: (2, 3, 2)


In [ ]:
#8/9.
import copy
import numpy as np

array = np.linspace(0, 20, 6)
copyArray = copy.deepcopy(array) 

print(copyArray)

[ 0.  4.  8. 12. 16. 20.]


In [ ]:
#10-12.
import pandas as pd
import numpy as np

array1 = np.array([[25, 26]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate([array1, array2, array3], axis = 0)
print("New Array:\n",newArray)

newArray.sort()
sortedArray = newArray
print("Sorted Array:\n", sortedArray)
reshapedArray = sortedArray

indexZero = reshapedArray[0]
indexOne = reshapedArray[1]
indexTwo = reshapedArray[2]
indexThree = reshapedArray[3]

print("First Element:", indexZero)
print("Second Element:", indexOne)
print("Third Element:", indexTwo)
print("Fourth Element:", indexThree)

New Array:
 [[25 26]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
Sorted Array:
 [[25 26]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]
First Element: [25 26]
Second Element: [ 2 11]
Third Element: [ 4 13]
Fourth Element: [ 7 81]


In [ ]:
#13/14.
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = one + two + three

sec1 = comboArray[1]
print("Sec1:", sec1)
sec2 = comboArray[2:len(comboArray)]
print("Sec2:", sec2)
sec3 = comboArray[3:15]
print("Sec3:", sec3)
sec4 = comboArray[-6:len(comboArray)]
print("Sec4:", sec4)
sec5 = comboArray[-len(comboArray):-8]
print("Sec5:", sec5)
sec6 = [number for number in comboArray[20:len(comboArray)] if number % 2 == 0]
print("Sec6:", sec6)
sec7 = comboArray[::-5]
print(sec7)

Sec1: 11
Sec2: [12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7]
Sec3: [13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26]
Sec4: [2, 3, 4, 5, 6, 7]
Sec5: [10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]
Sec6: [4, 6]
[7, 2, 25, 20, 13]


In [7]:
#15
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'])
quantity = pd.Series([4, 1, 2, 1])
unit = pd.Series(['cups', 'cup', 'large', 'can'])

recipe = pd.concat({
    'Ingredients': ingredients,
    'Quantity': quantity,
    'Unit': unit}, axis = 1)

dinner = pd.DataFrame(recipe)
#dinner = pd.DataFrame(recipe, index=['Ingredients', 'Quantity', 'Unit'])
print(dinner)
#dinner = dinner.set_index('Ingredients')
#dinner.name('Dinner') 
#print(dinner)


  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [31]:
#16-18.
import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    #'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)

dessert = ['ice cream', 'Cashew Fudge', 'waffles', 'Carrot Halwa']
studentData['Dessert'] = dessert
#print(studentData)
studentData = studentData.sort_values(by=['Name', 'Address'], ascending=True)
print (studentData)


      Name  Height Qualification  Address  Age           Sport
0      Jai     5.1           Msc    Delhi   21           Darts
1  janusha     6.2            MA     Doha   23      Basketball
2   Gaurav     5.1           Msc  Chennai   24  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21         Cricket
      Name  Height Qualification  Address  Age           Sport       Dessert
3     Anuj     5.2           Msc   Dakhar   21         Cricket  Carrot Halwa
2   Gaurav     5.1           Msc  Chennai   24  PaddleBoarding       waffles
0      Jai     5.1           Msc    Delhi   21           Darts     ice cream
1  janusha     6.2            MA     Doha   23      Basketball  Cashew Fudge


In [1]:
#19.
import pandas as pd
import os

df = pd.DataFrame({'Cows': [12, 20], 
                   'Goats': [22, 19]}, 
                   index=['Year 1', 'Year 2'])

print(df)
df.to_csv('cows_and_goats.csv', index=True)



        Cows  Goats
Year 1    12     22
Year 2    20     19


In [ ]:
#20.
import pandas as pd

veggies = pd.DataFrame({'Vegetable': ['Cauliflower', 'Zucchini', 'Broccoli', 'Tomato', 'Cucumber', 'Peppers'],
        'Color': ['White', 'Green', 'Green', 'Red', 'Green', 'Red'],
        'Nutrient': ['Vitamin A', 'Iron', 'Vitamin C', 'Vitamin C', 'Vitamin K', 'Vitamin A'],
    })

print(veggies)
veggies.to_csv('vegetableData.csv', index=True)

veggiesUpdate = pd.read_csv('vegetableData.csv')
organicStatus = [True, False, True, False, True, False]
veggiesUpdate['Organic'] = organicStatus
veggiesUpdate.to_csv('vegetablesUpdate.csv', index = False)
print(veggiesUpdate)



     Vegetable  Color   Nutrient
0  Cauliflower  White  Vitamin A
1     Zucchini  Green       Iron
2     Broccoli  Green  Vitamin C
3       Tomato    Red  Vitamin C
4     Cucumber  Green  Vitamin K
5      Peppers    Red  Vitamin A
   Unnamed: 0    Vegetable  Color   Nutrient  Organic
0           0  Cauliflower  White  Vitamin A     True
1           1     Zucchini  Green       Iron    False
2           2     Broccoli  Green  Vitamin C     True
3           3       Tomato    Red  Vitamin C    False
4           4     Cucumber  Green  Vitamin K     True
5           5      Peppers    Red  Vitamin A    False
